BEGIN;
--
-- Create model Category
--
CREATE TABLE "cookbook_category" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(100) NOT NULL,
    "description" text NOT NULL);
--
-- Create model Recipe
--
CREATE TABLE "cookbook_recipe" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "description" text NOT NULL,
    "ingredients" varchar(2000) NOT NULL,
    "steps" text NOT NULL,
    "duration" integer NOT NULL CHECK ("duration" >= 0),
    "image" varchar(100) NULL,
    "add_date" timestamp with time zone NOT NULL,
    "author_id" bigint NOT NULL,
    "category_id" bigint NULL
    );
ALTER TABLE "cookbook_recipe" ADD CONSTRAINT "cookbook_recipe_category_id_bb7f8f45_fk_cookbook_category_id" FOREIGN KEY ("category_id") REFERENCES "cookbook_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cookbook_recipe_category_id_bb7f8f45" ON "cookbook_recipe" ("category_id");

--ALTER TABLE "cookbook_recipe" ADD CONSTRAINT "cookbook_recipe_author_id_8a2bc8a4_fk_users_customuser_id" FOREIGN KEY ("author_id") REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
--CREATE INDEX "cookbook_recipe_author_id_8a2bc8a4" ON "cookbook_recipe" ("author_id");

COMMIT;