# Generated by Django 4.2.6 on 2025-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('ingredients', models.CharField(default='...', max_length=2000)),
                ('steps', models.TextField(max_length=2000)),
                ('duration', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
